chore: attempt to deploy to gh pages

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -53,25 +53,28 @@ jobs:
         with:
           name: playwright-report
           path: ${{ env.HTML_REPORT_URL_PATH }}
-      - name: Push to GH Pages
-        timeout-minutes: 3
-        run: |
-          git add .
-          git commit -m "workflow: add HTML report for run-id ${{ github.run_id }} (attempt:  ${{ github.run_attempt }})"
+      - name: Deploy to GitHub Pages
+        id: deployment
+        uses: actions/deploy-pages@v1
+      # - name: Push to GH Pages
+      #   timeout-minutes: 3
+      #   run: |
+      #     git add .
+      #     git commit -m "workflow: add HTML report for run-id ${{ github.run_id }} (attempt:  ${{ github.run_attempt }})"
 
-          while true; do
-            git pull --rebase
-            if [ $? -ne 0 ]; then
-              echo "Failed to rebase. Please review manually."
-              exit 1
-            fi
+      #     while true; do
+      #       git pull --rebase
+      #       if [ $? -ne 0 ]; then
+      #         echo "Failed to rebase. Please review manually."
+      #         exit 1
+      #       fi
 
-            git push
-            if [ $? -eq 0 ]; then
-              echo "Successfully pushed HTML report to repo."
-              exit 0
-            fi
-          done
+      #       git push
+      #       if [ $? -eq 0 ]; then
+      #         echo "Successfully pushed HTML report to repo."
+      #         exit 0
+      #       fi
+      #     done
       - name: Output Report URL as Workflow Annotation
         run: |
           FULL_HTML_REPORT_URL=https://piotrzalejski.github.io/playwright-demo/$HTML_REPORT_URL_PATH
